import type {
  ChecklistJuridicoAtivoVersionado,
  TemplateJuridicoAtivoVersionado,
  TeseJuridicaAtivaVersionada,
} from "@/modules/peticoes/base-juridica-viva/domain/types";
import type {
  BlocoTemplateJuridico,
  EspecializacaoTemplateMateria,
  MateriaCanonica,
  TipoPecaCanonica,
} from "@/modules/peticoes/domain/geracao-minuta";

const DATA_BASE_PADRAO = "2026-04-02T00:00:00.000Z";

const BLOCOS_PADRAO: BlocoTemplateJuridico[] = [
  { id: "cabecalho", titulo: "Cabeçalho", orientacaoBase: "Endereçamento e identificação da peça." },
  {
    id: "qualificacao_identificacao",
    titulo: "Qualificação e identificação",
    orientacaoBase: "Qualificação das partes e identificação do caso.",
  },
  {
    id: "sintese_fatica",
    titulo: "Síntese fática",
    orientacaoBase: "Cronologia objetiva dos fatos relevantes com suporte documental.",
  },
  {
    id: "fundamentos",
    titulo: "Fundamentos",
    orientacaoBase: "Fundamentação jurídica alinhada à estratégia consolidada.",
  },
  {
    id: "pedidos",
    titulo: "Pedidos",
    orientacaoBase: "Pedidos coerentes com a tese e o acervo documental.",
  },
  {
    id: "fechamento",
    titulo: "Fechamento",
    orientacaoBase: "Requerimentos finais, local e data.",
  },
];

const ESPECIALIZACAO_POR_MATERIA: Record<MateriaCanonica, EspecializacaoTemplateMateria> = {
  civel: {
    diretrizFundamentos: "Priorizar estrutura clássica de responsabilidade, inadimplemento e tutela jurisdicional adequada.",
    diretrizPedidos: "Manter pedidos certos, determinados e compatíveis com tutela de urgência quando cabível.",
    termosPreferenciais: ["responsabilidade civil", "inadimplemento", "ônus probatório"],
  },
  trabalhista: {
    diretrizFundamentos: "Fundamentar com base na CLT, súmulas e OJs do TST, priorizando princípio protetivo e primazia da realidade.",
    diretrizPedidos: "Incluir verbas trabalhistas específicas, reflexos e contribuições previdenciárias incidentes.",
    termosPreferenciais: ["vínculo empregatício", "jornada", "verbas rescisórias", "princípio protetivo"],
  },
  tributario: {
    diretrizFundamentos: "Demonstrar ilegalidade/inconstitucionalidade da exigência fiscal com suporte em jurisprudência do STF/STJ.",
    diretrizPedidos: "Requerer suspensão da exigibilidade, compensação ou restituição de indébito tributário.",
    termosPreferenciais: ["legalidade tributária", "não-cumulatividade", "base de cálculo", "fato gerador"],
  },
  criminal: {
    diretrizFundamentos: "Fundamentar em princípios de presunção de inocência, proporcionalidade e adequação da resposta penal.",
    diretrizPedidos: "Requerer absolvição, desclassificação ou aplicação de medidas alternativas quando cabível.",
    termosPreferenciais: ["presunção de inocência", "proporcionalidade", "tipicidade", "autoria"],
  },
  consumidor: {
    diretrizFundamentos: "Aplicar CDC com inversão do ônus da prova, responsabilidade objetiva e boa-fé contratual.",
    diretrizPedidos: "Incluir danos materiais e morais, obrigação de fazer/não fazer e multa cominatória.",
    termosPreferenciais: ["vulnerabilidade", "vício do produto", "prática abusiva", "inversão do ônus"],
  },
  empresarial: {
    diretrizFundamentos: "Fundamentar em direito societário, governança corporativa e preservação da empresa.",
    diretrizPedidos: "Requerer apuração de haveres, prestação de contas e medidas cautelares sobre patrimônio societário.",
    termosPreferenciais: ["affectio societatis", "apuração de haveres", "governança", "contrato social"],
  },
  familia: {
    diretrizFundamentos: "Priorizar princípio do melhor interesse da criança e binômio necessidade-possibilidade.",
    diretrizPedidos: "Incluir pedidos de fixação/revisão de alimentos, guarda, regulamentação de visitas.",
    termosPreferenciais: ["melhor interesse", "necessidade-possibilidade", "convivência familiar", "alimentos"],
  },
  ambiental: {
    diretrizFundamentos: "Fundamentar em princípios de precaução, prevenção e responsabilidade objetiva ambiental.",
    diretrizPedidos: "Requerer reparação do dano, medidas compensatórias e abstenção de atividade lesiva.",
    termosPreferenciais: ["precaução", "reparação integral", "licenciamento", "APP"],
  },
  agrario_agronegocio: {
    diretrizFundamentos:
      "Enfatizar dinâmica produtiva, sazonalidade, cadeia de suprimentos e impactos operacionais no campo.",
    diretrizPedidos:
      "Incluir providências para preservar atividade produtiva, fluxo logístico e equilíbrio contratual no agronegócio.",
    termosPreferenciais: ["safra", "insumo", "cadeia produtiva", "atividade rural"],
  },
  bancario: {
    diretrizFundamentos:
      "Destacar relação contratual financeira, boa-fé objetiva, dever de informação e regularidade de encargos.",
    diretrizPedidos:
      "Precisar revisão de encargos, exibição de evolução contratual e eventuais medidas de urgência contra negativação indevida.",
    termosPreferenciais: ["encargos", "capitalização", "boa-fé objetiva", "transparência contratual"],
  },
};

function templatePadrao(input: {
  id: string;
  codigo: string;
  nome: string;
  tipoPeca: TipoPecaCanonica;
  fundamentos: string[];
  pedidos: string[];
}): TemplateJuridicoAtivoVersionado {
  return {
    id: input.id,
    codigo: input.codigo,
    tipo: "template",
    nome: input.nome,
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: [input.tipoPeca],
    materias: ["civel", "trabalhista", "tributario", "criminal", "consumidor", "empresarial", "familia", "ambiental", "agrario_agronegocio", "bancario"],
    blocos: BLOCOS_PADRAO,
    clausulasBase: {
      fundamentos: input.fundamentos,
      pedidos: input.pedidos,
    },
    especializacaoPorMateria: ESPECIALIZACAO_POR_MATERIA,
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  };
}

const TEMPLATES_PADRAO: TemplateJuridicoAtivoVersionado[] = [
  templatePadrao({
    id: "tpl-peticao-inicial-v1",
    codigo: "tpl-peticao-inicial",
    nome: "Template Petição Inicial",
    tipoPeca: "peticao_inicial",
    fundamentos: [
      "Expor competência, legitimidade e interesse processual com base nos elementos do caso.",
      "Demonstrar probabilidade do direito e risco de dano para tutela de urgência, quando aplicável.",
    ],
    pedidos: [
      "Recebimento da petição inicial e citação da parte ré.",
      "Procedência integral dos pedidos com condenação principal e consectários legais.",
    ],
  }),
  templatePadrao({
    id: "tpl-contestacao-v1",
    codigo: "tpl-contestacao",
    nome: "Template Contestação",
    tipoPeca: "contestacao",
    fundamentos: [
      "Organizar preliminares processuais antes da impugnação de mérito.",
      "Rebater fatos constitutivos com contraprova documental e inconsistências narrativas.",
    ],
    pedidos: [
      "Acolhimento das preliminares suscitadas, quando pertinentes.",
      "Improcedência dos pedidos iniciais e condenação da parte autora em ônus sucumbenciais.",
    ],
  }),
  templatePadrao({
    id: "tpl-manifestacao-v1",
    codigo: "tpl-manifestacao",
    nome: "Template Manifestação",
    tipoPeca: "manifestacao",
    fundamentos: [
      "Responder objetivamente aos pontos determinados em despacho ou decisão.",
      "Conectar cada argumento às referências documentais consolidadas no contexto.",
    ],
    pedidos: [
      "Recebimento da manifestação para os fins processuais cabíveis.",
      "Adoção das providências requeridas ao final da peça.",
    ],
  }),
  templatePadrao({
    id: "tpl-embargos-execucao-v1",
    codigo: "tpl-embargos-execucao",
    nome: "Template Embargos à Execução",
    tipoPeca: "embargos_execucao",
    fundamentos: [
      "Delimitar excesso, inexigibilidade ou nulidade da execução com memória de cálculo e documentos.",
      "Apresentar impugnação técnica dos títulos e encargos executados.",
    ],
    pedidos: [
      "Recebimento e processamento dos embargos à execução.",
      "Reconhecimento da inexigibilidade total ou parcial e adequação dos valores executados.",
    ],
  }),
  templatePadrao({
    id: "tpl-apelacao-civel-v1",
    codigo: "tpl-apelacao-civel",
    nome: "Template Apelação Cível",
    tipoPeca: "apelacao_civel",
    fundamentos: [
      "Demonstrar error in judicando e/ou error in procedendo de forma segmentada.",
      "Evidenciar violação ao conjunto probatório e ao enquadramento jurídico adotado na sentença.",
    ],
    pedidos: [
      "Conhecimento e provimento do recurso para reforma integral ou parcial da sentença.",
      "Redistribuição dos ônus sucumbenciais conforme resultado recursal.",
    ],
  }),
  templatePadrao({
    id: "tpl-recurso-especial-civel-v1",
    codigo: "tpl-recurso-especial-civel",
    nome: "Template Recurso Especial Cível",
    tipoPeca: "recurso_especial_civel",
    fundamentos: [
      "Indicar violação direta de dispositivo federal e o prequestionamento correspondente.",
      "Estruturar demonstração analítica de divergência jurisprudencial quando aplicável.",
    ],
    pedidos: [
      "Admissão do recurso especial por preenchimento dos pressupostos legais.",
      "Provimento para adequação do acórdão recorrido ao entendimento da legislação federal.",
    ],
  }),
  templatePadrao({
    id: "tpl-agravo-instrumento-v1",
    codigo: "tpl-agravo-instrumento",
    nome: "Template Agravo de Instrumento",
    tipoPeca: "agravo_instrumento",
    fundamentos: [
      "Demonstrar a recorribilidade imediata da decisão interlocutória conforme art. 1.015 do CPC.",
      "Evidenciar o erro na concessão ou denegação da tutela provisória e o risco de dano irreparável.",
    ],
    pedidos: [
      "Conhecimento e provimento do agravo de instrumento para reforma da decisão agravada.",
      "Concessão de efeito suspensivo ativo para sustar imediatamente os efeitos da decisão.",
    ],
  }),
  templatePadrao({
    id: "tpl-tutela-urgencia-v1",
    codigo: "tpl-tutela-urgencia",
    nome: "Template Tutela de Urgência",
    tipoPeca: "tutela_urgencia",
    fundamentos: [
      "Demonstrar probabilidade do direito com base em prova documental robusta.",
      "Evidenciar perigo de dano ou risco ao resultado útil do processo (periculum in mora).",
    ],
    pedidos: [
      "Concessão inaudita altera pars da tutela de urgência requerida.",
      "Determinação de medida específica para preservação do direito até julgamento final.",
    ],
  }),
  templatePadrao({
    id: "tpl-mandado-seguranca-v1",
    codigo: "tpl-mandado-seguranca",
    nome: "Template Mandado de Segurança",
    tipoPeca: "mandado_seguranca",
    fundamentos: [
      "Identificar autoridade coatora, ato ilegal ou abusivo e direito líquido e certo violado.",
      "Demonstrar ausência de recurso administrativo com efeito suspensivo adequado.",
    ],
    pedidos: [
      "Concessão de liminar suspendendo os efeitos do ato impugnado.",
      "Segurança definitiva para anular ou corrigir o ato coator e restabelecer o direito.",
    ],
  }),
  templatePadrao({
    id: "tpl-reconvencao-v1",
    codigo: "tpl-reconvencao",
    nome: "Template Reconvenção",
    tipoPeca: "reconvencao",
    fundamentos: [
      "Demonstrar conexão da reconvenção com a ação principal ou com o fundamento da defesa.",
      "Apresentar causa de pedir autônoma que resulte em pedido reconvencional determinado.",
    ],
    pedidos: [
      "Recebimento e processamento da reconvenção em conjunto com a contestação.",
      "Procedência do pedido reconvencional com condenação da parte autora-reconvinda.",
    ],
  }),
  templatePadrao({
    id: "tpl-embargos-declaracao-v1",
    codigo: "tpl-embargos-declaracao",
    nome: "Template Embargos de Declaração",
    tipoPeca: "embargos_declaracao",
    fundamentos: [
      "Apontar obscuridade, contradição, omissão ou erro material específicos na decisão.",
      "Indicar necessidade de prequestionamento para fins recursais quando aplicável.",
    ],
    pedidos: [
      "Conhecimento e provimento dos embargos para sanar o vício apontado.",
      "Integração da decisão com fundamento sobre ponto omitido, contradição ou obscuridade.",
    ],
  }),
  templatePadrao({
    id: "tpl-contrarrazoes-v1",
    codigo: "tpl-contrarrazoes",
    nome: "Template Contrarrazões Recursais",
    tipoPeca: "contrarrazoes",
    fundamentos: [
      "Rebater sistematicamente cada fundamento do recurso adverso com apoio documental.",
      "Reforçar a correção da decisão recorrida com base na prova produzida e no direito aplicado.",
    ],
    pedidos: [
      "Conhecimento das contrarrazões e manutenção integral da decisão recorrida.",
      "Majoração dos honorários sucumbenciais na forma do art. 85, §11, do CPC.",
    ],
  }),
  templatePadrao({
    id: "tpl-excecao-pre-executividade-v1",
    codigo: "tpl-excecao-pre-executividade",
    nome: "Template Exceção de Pré-Executividade",
    tipoPeca: "excecao_pre_executividade",
    fundamentos: [
      "Demonstrar matéria de ordem pública cognoscível de ofício pelo juiz (prescrição, nulidade do título, ilegitimidade).",
      "Evidenciar que a arguição dispensa dilação probatória por ser aferível de plano pelos documentos dos autos.",
    ],
    pedidos: [
      "Extinção da execução por acolhimento da exceção de pré-executividade.",
      "Condenação da parte exequente nas verbas de sucumbência.",
    ],
  }),

  // ─── Template especializado — Operação Mata-Mata ───────────────────────────
  {
    id: "tpl-embargos-execucao-credito-rural-v1",
    codigo: "tpl-embargos-execucao-credito-rural",
    tipo: "template",
    nome: "Template Embargos à Execução — Crédito Rural (Operação Mata-Mata)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao"],
    materias: ["bancario", "agrario_agronegocio"],
    blocos: [
      {
        id: "cabecalho",
        titulo: "Cabeçalho",
        orientacaoBase: "Endereçamento ao juízo da execução. Identificar processo de origem, vara, número e valor executado.",
      },
      {
        id: "qualificacao_partes",
        titulo: "Qualificação das Partes",
        orientacaoBase: "Qualificar o embargante (produtor rural) com CPF/CNPJ, NIRF, endereço da propriedade rural. Qualificar o embargado (banco) com CNPJ e sede. Mencionar o título executado (CCB/CCR) com número e data.",
      },
      {
        id: "tempestividade_garantia",
        titulo: "Tempestividade e Garantia do Juízo",
        orientacaoBase: "Demonstrar que os embargos são tempestivos (15 dias da intimação da penhora, art. 915 do CPC). Confirmar penhora ou garantia suficiente. Requerer efeito suspensivo com fundamento em probabilidade do direito e risco de dano grave (art. 919, §1º, CPC).",
      },
      {
        id: "sintese_fatica_operacao",
        titulo: "Síntese Fática — A Operação Mata-Mata",
        orientacaoBase: "Descrever cronologicamente: (1) o crédito original (data, valor, banco, finalidade declarada); (2) a primeira renegociação e incorporação de encargos; (3) a operação mata-mata (data de contratação do novo CCB/CCR, valor, e prova de que os recursos foram imediatamente usados para quitar o crédito anterior); (4) o exequível (valor, encargos, penhora decretada). Referenciar documentos por DOC-XXX.",
      },
      {
        id: "nulidade_simulacao",
        titulo: "I — Nulidade do Título: Simulação e Desvio de Finalidade",
        orientacaoBase: "Demonstrar que a operação configura negócio jurídico simulado (art. 167, CC): (a) ausência de disponibilidade real dos recursos ao mutuário; (b) liquidação simultânea do contrato anterior; (c) desvio da finalidade do crédito rural regulado (art. 49, DL 167/67). Citar o REsp 1.061.530/RS e a Ap. nº 193.221.447 – 9ª Câmara como paradigmas. Requerer nulidade do título e extinção da execução.",
      },
      {
        id: "revisao_cadeia",
        titulo: "II — Revisão da Cadeia de Crédito (Súmula 286/STJ)",
        orientacaoBase: "Com base na Súmula 286/STJ, demonstrar que a renegociação não afasta a discussão sobre ilegalidades dos contratos anteriores. Mapear encargos ilegais incorporados em cada repactuação: capitalização não pactuada, CDI (Súmula 176/STJ), mora acima de 1% a.a. (art. 5º, DL 167/67). Apresentar cálculo comparativo do saldo exigível vs. saldo com expurgo dos encargos ilegais.",
      },
      {
        id: "alongamento",
        titulo: "III — Direito ao Alongamento e Inexigibilidade Atual (Súmula 298/STJ)",
        orientacaoBase: "Se o banco opera com recursos controlados do MCR, demonstrar o direito ao alongamento/securitização da dívida rural (Lei 9.138/95, Súmula 298/STJ). Evidenciar que a negativa de prorrogação foi ilegal e que a dívida não é exigível na forma executada. Requerer suspensão da execução enquanto não apreciado o pedido de alongamento.",
      },
      {
        id: "excesso_encargos",
        titulo: "IV — Excesso de Execução e Encargos Ilegais",
        orientacaoBase: "Demonstrar item a item os encargos ilegais no título: (a) juros acima dos limites do CMN para crédito rural; (b) capitalização de juros não autorizada; (c) comissão de permanência acumulada com multa e juros moratórios (Súmulas 294/296/STJ); (d) mora acima de 1% a.a. (art. 5º DL 167/67); (e) indexação por CDI (Súmula 176/STJ). Apresentar planilha de cálculo com expurgo e saldo correto. Requerer penhora/execução limitada ao saldo revisado.",
      },
      {
        id: "impenhorabilidade",
        titulo: "V — Impenhorabilidade dos Bens Constritos",
        orientacaoBase: "Se aplicável: (a) impenhorabilidade da pequena propriedade rural familiar (art. 5º, XXVI, CF); (b) impenhorabilidade de produto rural vinculado a CPR ou CCR anterior (art. 17, DL 167/67); (c) impenhorabilidade de instrumentos de trabalho necessários à atividade rural (art. 833, V, CPC). Requerer substituição de penhora ou levantamento da constrição sobre bens impenhoráveis.",
      },
      {
        id: "pedidos",
        titulo: "Pedidos",
        orientacaoBase: "Formular pedidos em ordem de preferência: (1) extinção da execução por nulidade do título (simulação); (2) subsidiariamente, reconhecimento do direito ao alongamento e suspensão da execução; (3) revisão da cadeia de crédito com expurgo dos encargos ilegais e limitação da execução ao saldo correto; (4) levantamento ou substituição de penhora sobre bens impenhoráveis; (5) condenação da exequente em honorários e custas.",
      },
      {
        id: "fechamento",
        titulo: "Fechamento",
        orientacaoBase: "Local, data, OAB do advogado. Requerimento de intimação eletrônica.",
      },
    ],
    clausulasBase: {
      fundamentos: [
        "O título executado é nulo por configurar negócio jurídico simulado (art. 167 do CC): os recursos não foram disponibilizados ao produtor rural para fomento da atividade produtiva, mas usados imediatamente para quitar débito pretérito do mesmo mutuário perante o mesmo credor.",
        "A Súmula 286/STJ autoriza a revisão de toda a cadeia de crédito: renegociações e repactuações anteriores não afastam a discussão sobre ilegalidades dos contratos-base, especialmente encargos que excedem os limites fixados pelo CMN para crédito rural.",
        "Os juros de mora em crédito rural estão limitados a 1% ao ano (art. 5º, DL 167/67), sendo nula qualquer cláusula que estabeleça mora superior, bem como a cumulação de comissão de permanência com multa e juros moratórios (Súmulas 294 e 296/STJ).",
        "A indexação pelo CDI é nula em crédito rural por força da Súmula 176/STJ, que proíbe a utilização de taxa de juros divulgada pela ANBID/CETIP como indexador, devendo ser substituída por índice oficial de correção monetária.",
      ],
      pedidos: [
        "Recebimento e processamento dos embargos à execução, com concessão de efeito suspensivo nos termos do art. 919, §1º, do CPC, dada a probabilidade do direito e o risco de dano grave com o prosseguimento da execução.",
        "Acolhimento do pedido principal de nulidade do título executado por simulação e desvio de finalidade do crédito rural, com extinção da execução.",
        "Subsidiariamente, revisão de toda a cadeia de crédito com expurgo dos encargos ilegais (mora acima de 1% a.a., CDI, capitalização não autorizada, comissão de permanência cumulada), limitando a execução ao saldo correto apurado em perícia contábil.",
        "Levantamento ou substituição de penhora recaída sobre bem impenhorável, com condenação da exequente nas custas processuais e honorários advocatícios.",
      ],
    },
    especializacaoPorMateria: ESPECIALIZACAO_POR_MATERIA,
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
];

const TESES_PADRAO: TeseJuridicaAtivaVersionada[] = [
  {
    id: "tese-civ-001-v1",
    codigo: "TES-CIV-001",
    tipo: "tese",
    titulo: "Tutela de urgência por risco de dano contratual contínuo",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "manifestacao"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    palavrasChave: ["tutela de urgência", "risco", "inadimplemento", "probabilidade do direito"],
    gatilhos: [
      { id: "GAT-CIV-001", tipo: "estrategia", valor: "risco", peso: 5 },
      { id: "GAT-CIV-002", tipo: "ponto_controvertido", valor: "inadimplemento", peso: 4 },
      { id: "GAT-CIV-003", tipo: "padrao_textual", valor: "tutela", peso: 3 },
      { id: "GAT-CIV-004", tipo: "referencia_documental", valor: "DOC", peso: 2 },
    ],
    teseBase: "A urgência é justificada pelo dano progressivo e pela plausibilidade documental da narrativa fática.",
    fundamentoSintetico: "Art. 300 do CPC e princípio da efetividade da tutela jurisdicional.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-civ-002-v1",
    codigo: "TES-CIV-002",
    tipo: "tese",
    titulo: "Responsabilidade por descumprimento contratual com prova documental",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "apelacao_civel"],
    materias: ["civel", "agrario_agronegocio"],
    palavrasChave: ["descumprimento", "cláusula", "multa", "prova documental"],
    gatilhos: [
      { id: "GAT-CIV-005", tipo: "ponto_controvertido", valor: "descumpr", peso: 4 },
      { id: "GAT-CIV-006", tipo: "referencia_documental", valor: "contrato", peso: 4 },
      { id: "GAT-CIV-007", tipo: "palavra_chave", valor: "multa", peso: 3 },
    ],
    teseBase: "A violação contratual comprovada por documentos autoriza condenação e reparação integral.",
    fundamentoSintetico: "Boa-fé objetiva e força obrigatória dos contratos.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-001-v1",
    codigo: "TES-BAN-001",
    tipo: "tese",
    titulo: "Revisão de encargos e transparência contratual bancária",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "embargos_execucao"],
    materias: ["bancario"],
    palavrasChave: ["encargos", "capitalização", "transparência", "boa-fé objetiva"],
    gatilhos: [
      { id: "GAT-BAN-001", tipo: "palavra_chave", valor: "encargos", peso: 4 },
      { id: "GAT-BAN-002", tipo: "estrategia", valor: "revisão", peso: 4 },
      { id: "GAT-BAN-003", tipo: "ponto_controvertido", valor: "capitalização", peso: 3 },
    ],
    teseBase: "A ausência de clareza na evolução da dívida impõe revisão dos encargos e exibição analítica.",
    fundamentoSintetico: "Dever de informação e vedação de vantagem excessiva.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-001-v1",
    codigo: "TES-AGR-001",
    tipo: "tese",
    titulo: "Preservação da atividade produtiva no agronegócio",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "manifestacao", "apelacao_civel"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["safra", "atividade rural", "insumo", "cadeia produtiva"],
    gatilhos: [
      { id: "GAT-AGR-001", tipo: "palavra_chave", valor: "safra", peso: 4 },
      { id: "GAT-AGR-002", tipo: "estrategia", valor: "atividade produtiva", peso: 4 },
      { id: "GAT-AGR-003", tipo: "ponto_controvertido", valor: "insumo", peso: 3 },
    ],
    teseBase: "A tutela jurisdicional deve evitar interrupção da cadeia produtiva e perda da safra.",
    fundamentoSintetico: "Função social da atividade produtiva e proteção da continuidade do negócio rural.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-def-001-v1",
    codigo: "TES-DEF-001",
    tipo: "tese",
    titulo: "Impugnação por insuficiência probatória da parte adversa",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["contestacao", "manifestacao"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    palavrasChave: ["ônus da prova", "insuficiência", "impugnação específica"],
    gatilhos: [
      { id: "GAT-DEF-001", tipo: "padrao_textual", valor: "ônus", peso: 3 },
      { id: "GAT-DEF-002", tipo: "ponto_controvertido", valor: "prova", peso: 4 },
      { id: "GAT-DEF-003", tipo: "estrategia", valor: "impugnação", peso: 3 },
    ],
    teseBase: "A narrativa adversa sem prova robusta deve ser rejeitada por ausência de suporte mínimo.",
    fundamentoSintetico: "Distribuição dinâmica/estática do ônus probatório conforme CPC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-rec-001-v1",
    codigo: "TES-REC-001",
    tipo: "tese",
    titulo: "Reforma por error in judicando com revaloração do conjunto fático",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["apelacao_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    palavrasChave: ["error in judicando", "reforma", "conjunto probatório"],
    gatilhos: [
      { id: "GAT-REC-001", tipo: "padrao_textual", valor: "reforma", peso: 4 },
      { id: "GAT-REC-002", tipo: "ponto_controvertido", valor: "sentença", peso: 3 },
      { id: "GAT-REC-003", tipo: "estrategia", valor: "recurso", peso: 3 },
    ],
    teseBase: "A sentença deve ser reformada quando dissociada da prova documental e dos fatos incontroversos.",
    fundamentoSintetico: "Controle de legalidade e correção do julgamento em segundo grau.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-esp-001-v1",
    codigo: "TES-ESP-001",
    tipo: "tese",
    titulo: "Violação de dispositivo federal e prequestionamento",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["recurso_especial_civel"],
    materias: ["civel", "bancario"],
    palavrasChave: ["dispositivo federal", "prequestionamento", "recurso especial"],
    gatilhos: [
      { id: "GAT-ESP-001", tipo: "padrao_textual", valor: "dispositivo federal", peso: 5 },
      { id: "GAT-ESP-002", tipo: "padrao_textual", valor: "prequestionamento", peso: 4 },
      { id: "GAT-ESP-003", tipo: "estrategia", valor: "recurso especial", peso: 3 },
    ],
    teseBase: "A admissibilidade recursal depende da demonstração analítica de violação legal e prequestionamento.",
    fundamentoSintetico: "Pressupostos de admissibilidade do recurso especial.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-emb-001-v1",
    codigo: "TES-EMB-001",
    tipo: "tese",
    titulo: "Excesso de execução e inexigibilidade parcial",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao"],
    materias: ["civel", "bancario"],
    palavrasChave: ["excesso de execução", "inexigibilidade", "memória de cálculo"],
    gatilhos: [
      { id: "GAT-EMB-001", tipo: "palavra_chave", valor: "excesso", peso: 4 },
      { id: "GAT-EMB-002", tipo: "palavra_chave", valor: "inexigibilidade", peso: 4 },
      { id: "GAT-EMB-003", tipo: "referencia_documental", valor: "cálculo", peso: 3 },
    ],
    teseBase: "A execução deve ser limitada ao valor efetivamente exigível, com abatimento de parcelas indevidas.",
    fundamentoSintetico: "Devido processo executivo e liquidez estrita do título.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-002-v1",
    codigo: "TES-AGR-002",
    tipo: "tese",
    titulo: "Usucapião Especial Rural (Pro Labore) - Função Social",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["usucapião rural", "pro labore", "função social", "trabalho familiar"],
    gatilhos: [
      { id: "GAT-AGR-004", tipo: "palavra_chave", valor: "usucapião", peso: 5 },
      { id: "GAT-AGR-005", tipo: "estrategia", valor: "função social", peso: 4 },
      { id: "GAT-AGR-006", tipo: "referencia_documental", valor: "CAR", peso: 3 },
    ],
    teseBase: "O cumprimento cumulativo dos requisitos constitucionais — área inferior a 50ha, moradia e exploração com trabalho familiar — enseja a aquisição originária independentemente de justo título.",
    fundamentoSintetico: "Art. 191 da CF/88 e Art. 1.239 do CC — Prevalência do direito à terra por quem a torna produtiva.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-003-v1",
    codigo: "TES-AGR-003",
    tipo: "tese",
    titulo: "Reintegração de Posse por Invasão Rural (Força Nova)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["agrario_agronegocio", "civel"],
    palavrasChave: ["esbulho", "invasão", "força nova", "força policial", "reintegração"],
    gatilhos: [
      { id: "GAT-AGR-007", tipo: "palavra_chave", valor: "esbulho", peso: 4 },
      { id: "GAT-AGR-008", tipo: "estrategia", valor: "reintegração", peso: 5 },
      { id: "GAT-AGR-009", tipo: "ponto_controvertido", valor: "invasão", peso: 4 },
    ],
    teseBase: "Comprovada a posse anterior, a ocorrência de agressão clandestina e o esbulho consolidado a menos de ano e dia, é imperativa a concessão de liminar, com auxílio de força policial, ante o risco ao patrimônio e ordem pública.",
    fundamentoSintetico: "Art. 561 e 562 do CPC (Ação de força nova posseutória).",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-004-v1",
    codigo: "TES-AGR-004",
    tipo: "tese",
    titulo: "Direito de Retenção por Benfeitorias no Arrendamento Rural",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["arrendamento", "retenção", "benfeitorias", "estatuto da terra"],
    gatilhos: [
      { id: "GAT-AGR-010", tipo: "palavra_chave", valor: "retenção", peso: 4 },
      { id: "GAT-AGR-011", tipo: "referencia_documental", valor: "Estatuto da Terra", peso: 3 },
      { id: "GAT-AGR-012", tipo: "ponto_controvertido", valor: "benfeitorias", peso: 4 },
    ],
    teseBase: "A restituição do imóvel rural objeto de arrendamento fica condicionada ao prévio adimplemento financeiro das benfeitorias úteis e necessárias implementadas de boa-fé, cabendo direito de retenção integral pelo posseiro.",
    fundamentoSintetico: "Art. 95, VIII, Lei nº 4.504/1964 (Estatuto da Terra).",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-005-v1",
    codigo: "TES-AGR-005",
    tipo: "tese",
    titulo: "Liquidez da CPR e Arresto Cautelar de Grãos",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "tutela_urgencia"],
    materias: ["agrario_agronegocio", "empresarial"],
    palavrasChave: ["CPR", "arresto", "cédula de produto rural", "liquidez"],
    gatilhos: [
      { id: "GAT-AGR-013", tipo: "palavra_chave", valor: "CPR", peso: 5 },
      { id: "GAT-AGR-014", tipo: "palavra_chave", valor: "arresto", peso: 4 },
      { id: "GAT-AGR-015", tipo: "estrategia", valor: "cautelar", peso: 3 },
    ],
    teseBase: "O inadimplemento de obrigação certa, líquida e exigível materializada em Cédula de Produto Rural enseja não só a execução célere do título, mas também eventual tutela cautelar de arresto em vista de fundado receio de dilapidação e comercialização dos grãos em armazéns de terceiros.",
    fundamentoSintetico: "Art. 4º da Lei 8.929/1994 c/c Art. 301 do CPC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-006-v1",
    codigo: "TES-AGR-006",
    tipo: "tese",
    titulo: "Impenhorabilidade da Pequena Propriedade Rural Familiar",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "excecao_pre_executividade", "agravo_instrumento"],
    materias: ["agrario_agronegocio", "civel"],
    palavrasChave: ["impenhorabilidade", "pequena propriedade rural", "módulo fiscal", "subsistência familiar"],
    gatilhos: [
      { id: "GAT-AGR-016", tipo: "palavra_chave", valor: "impenhorabilidade", peso: 5 },
      { id: "GAT-AGR-017", tipo: "referencia_documental", valor: "módulo fiscal", peso: 4 },
      { id: "GAT-AGR-018", tipo: "estrategia", valor: "execução rural", peso: 3 },
    ],
    teseBase: "A pequena propriedade rural (área compreendida entre 1 e 4 módulos fiscais), quando explorada pela família e garantidora da sua subsistência, é absolutamente impenhorável para pagamento de dívidas decorrentes de sua atividade produtiva — norma de garantia constitucional incontornável.",
    fundamentoSintetico: "Art. 5º, inciso XXVI, da CF/88 c/c Art. 833, inciso VIII, do CPC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-007-v1",
    codigo: "TES-AGR-007",
    tipo: "tese",
    titulo: "Direito à Prorrogação do Débito Rural (Securitização)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["mandado_seguranca", "peticao_inicial", "tutela_urgencia"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["prorrogação", "securitização", "súmula 298", "crédito rural", "mandado de segurança"],
    gatilhos: [
      { id: "GAT-AGR-019", tipo: "palavra_chave", valor: "prorrogação", peso: 5 },
      { id: "GAT-AGR-020", tipo: "palavra_chave", valor: "Súmula 298", peso: 5 },
      { id: "GAT-AGR-021", tipo: "referencia_documental", valor: "laudo", peso: 3 },
    ],
    teseBase: "O alongamento de dívida originada de crédito rural não constitui faculdade da instituição financeira, mas direito do devedor nos termos da lei, quando preenchidos os requisitos exigidos (Súmula 298/STJ). A negativa bancária via agente operando com recursos controlados autoriza o Mandado de Segurança.",
    fundamentoSintetico: "Súmula 298 do STJ c/c Manual de Crédito Rural (MCR).",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Trabalhista ---
  {
    id: "tese-trab-001-v1",
    codigo: "TES-TRAB-001",
    tipo: "tese",
    titulo: "Reconhecimento de Vínculo Empregatício por Primazia da Realidade",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["trabalhista"],
    palavrasChave: ["vínculo empregatício", "primazia da realidade", "subordinação", "CLT"],
    gatilhos: [
      { id: "GAT-TRAB-001", tipo: "palavra_chave", valor: "vínculo", peso: 5 },
      { id: "GAT-TRAB-002", tipo: "estrategia", valor: "reconhecimento", peso: 4 },
    ],
    teseBase: "A presença dos requisitos fáticos de pessoa física, pessoalidade, onerosidade, não-eventualidade e subordinação impõe o reconhecimento do vínculo celetista, independentemente da roupagem formal adotada (PJ, autônomo, cooperado).",
    fundamentoSintetico: "Art. 3º e 442-B da CLT — Princípio da primazia da realidade sobre a forma.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-trab-002-v1",
    codigo: "TES-TRAB-002",
    tipo: "tese",
    titulo: "Horas Extras Habituais e Reflexos nas Verbas Trabalhistas",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["trabalhista"],
    palavrasChave: ["horas extras", "reflexos", "DSR", "férias", "13º salário"],
    gatilhos: [
      { id: "GAT-TRAB-003", tipo: "palavra_chave", valor: "horas extras", peso: 5 },
      { id: "GAT-TRAB-004", tipo: "estrategia", valor: "reflexos", peso: 4 },
    ],
    teseBase: "As horas extras habituais integram a remuneração para fins de DSR, férias com 1/3, 13º salário, aviso prévio indenizado e FGTS com multa de 40%, por força da Súmula 172 do TST.",
    fundamentoSintetico: "Arts. 7º e 59 da CLT c/c Súmula 172/TST.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-trab-003-v1",
    codigo: "TES-TRAB-003",
    tipo: "tese",
    titulo: "Dano Moral Trabalhista por Conduta Patronal Abusiva",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["trabalhista"],
    palavrasChave: ["dano moral", "assédio", "honra", "dignidade", "conduta patronal"],
    gatilhos: [
      { id: "GAT-TRAB-005", tipo: "palavra_chave", valor: "dano moral", peso: 5 },
      { id: "GAT-TRAB-006", tipo: "estrategia", valor: "conduta patronal", peso: 3 },
    ],
    teseBase: "A conduta patronal que expõe o empregado a vexame, humilhação pública ou violação sistemática da dignidade no ambiente de trabalho gera obrigação de reparação por dano moral, nos termos do art. 223-A e seguintes da CLT.",
    fundamentoSintetico: "Arts. 223-A a 223-G da CLT c/c art. 5º, X, da CF/88.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-trab-004-v1",
    codigo: "TES-TRAB-004",
    tipo: "tese",
    titulo: "Equiparação Salarial por Trabalho de Igual Valor",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["trabalhista"],
    palavrasChave: ["equiparação salarial", "paradigma", "mesma função", "isonomia"],
    gatilhos: [
      { id: "GAT-TRAB-007", tipo: "palavra_chave", valor: "equiparação", peso: 5 },
      { id: "GAT-TRAB-008", tipo: "estrategia", valor: "paradigma", peso: 4 },
    ],
    teseBase: "A equiparação salarial é devida quando o empregado exerce a mesma função do paradigma com igual produtividade e perfeição técnica, na mesma localidade, sem diferença de tempo superior a 4 anos na função nem 2 anos no emprego.",
    fundamentoSintetico: "Art. 461 da CLT c/c Súmula 6 do TST.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Consumidor ---
  {
    id: "tese-cons-001-v1",
    codigo: "TES-CONS-001",
    tipo: "tese",
    titulo: "Dano Moral por Inscrição Indevida em Cadastros de Inadimplentes",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["consumidor", "bancario", "civel"],
    palavrasChave: ["negativação indevida", "SPC", "SERASA", "dano moral", "abalo de crédito"],
    gatilhos: [
      { id: "GAT-CONS-001", tipo: "palavra_chave", valor: "negativação", peso: 5 },
      { id: "GAT-CONS-002", tipo: "estrategia", valor: "indevida", peso: 4 },
    ],
    teseBase: "A inscrição indevida em cadastro de inadimplentes configura dano moral in re ipsa, prescindindo de prova do prejuízo, por força da Súmula 385/STJ.",
    fundamentoSintetico: "Arts. 6º, VI e 43 do CDC c/c Súmula 385/STJ.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-cons-002-v1",
    codigo: "TES-CONS-002",
    tipo: "tese",
    titulo: "Responsabilidade Objetiva do Fornecedor por Vício do Produto",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["consumidor"],
    palavrasChave: ["vício do produto", "responsabilidade objetiva", "substituição", "restituição"],
    gatilhos: [
      { id: "GAT-CONS-003", tipo: "palavra_chave", valor: "vício", peso: 5 },
      { id: "GAT-CONS-004", tipo: "estrategia", valor: "produto", peso: 3 },
    ],
    teseBase: "O fornecedor responde objetivamente pelos vícios de qualidade do produto que o tornem impróprio ou inadequado ao consumo, cabendo ao consumidor optar pela substituição do produto, restituição da quantia paga ou abatimento proporcional.",
    fundamentoSintetico: "Art. 18 do CDC — Responsabilidade objetiva pelo vício do produto.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-cons-003-v1",
    codigo: "TES-CONS-003",
    tipo: "tese",
    titulo: "Inversão do Ônus da Prova em Favor do Consumidor",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao"],
    materias: ["consumidor"],
    palavrasChave: ["inversão do ônus", "hipossuficiência", "verossimilhança", "CDC"],
    gatilhos: [
      { id: "GAT-CONS-005", tipo: "estrategia", valor: "inversão", peso: 5 },
      { id: "GAT-CONS-006", tipo: "palavra_chave", valor: "ônus da prova", peso: 4 },
    ],
    teseBase: "A inversão do ônus da prova é técnica de facilitação da defesa do consumidor, deferível quando verossímil a alegação ou quando for hipossuficiente, transferindo ao fornecedor o encargo de provar a regularidade do produto ou serviço.",
    fundamentoSintetico: "Art. 6º, VIII do CDC — Direito básico do consumidor.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Família ---
  {
    id: "tese-fam-001-v1",
    codigo: "TES-FAM-001",
    tipo: "tese",
    titulo: "Fixação de Alimentos pelo Binômio Necessidade-Possibilidade",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao"],
    materias: ["familia"],
    palavrasChave: ["alimentos", "necessidade", "possibilidade", "binômio", "pensão"],
    gatilhos: [
      { id: "GAT-FAM-001", tipo: "palavra_chave", valor: "alimentos", peso: 5 },
      { id: "GAT-FAM-002", tipo: "estrategia", valor: "binômio", peso: 4 },
    ],
    teseBase: "A fixação dos alimentos deve ser pautada pelo binômio necessidade do alimentando e possibilidade do alimentante, garantindo o mínimo existencial sem comprometer a subsistência do obrigado.",
    fundamentoSintetico: "Art. 1.694 e 1.695 do CC — Proporcionalidade na fixação dos alimentos.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-fam-002-v1",
    codigo: "TES-FAM-002",
    tipo: "tese",
    titulo: "Guarda Compartilhada como Regra — Melhor Interesse da Criança",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["familia"],
    palavrasChave: ["guarda compartilhada", "melhor interesse", "convivência familiar", "ECA"],
    gatilhos: [
      { id: "GAT-FAM-003", tipo: "palavra_chave", valor: "guarda", peso: 5 },
      { id: "GAT-FAM-004", tipo: "estrategia", valor: "compartilhada", peso: 4 },
    ],
    teseBase: "A guarda compartilhada é a regra legal e deve ser aplicada sempre que ambos os genitores estejam aptos ao exercício do poder familiar, ainda que não haja acordo entre eles, privilegiando a convivência equilibrada com ambos.",
    fundamentoSintetico: "Art. 1.584, §2º do CC c/c art. 227 da CF/88 — Melhor interesse da criança.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-fam-003-v1",
    codigo: "TES-FAM-003",
    tipo: "tese",
    titulo: "Revisão de Alimentos por Alteração Superveniente de Condições",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["familia"],
    palavrasChave: ["revisão de alimentos", "alteração", "condições supervenientes", "reajuste"],
    gatilhos: [
      { id: "GAT-FAM-005", tipo: "palavra_chave", valor: "revisão de alimentos", peso: 5 },
      { id: "GAT-FAM-006", tipo: "estrategia", valor: "alteração de condições", peso: 4 },
    ],
    teseBase: "A revisão alimentar é cabível quando houver alteração na situação financeira de quem os supre ou de quem os recebe, demonstrada nos autos por documentação idônea, possibilitando exoneração, redução ou majoração.",
    fundamentoSintetico: "Art. 1.699 do CC — Mutabilidade dos alimentos por alteração das condições.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Tributário ---
  {
    id: "tese-trib-001-v1",
    codigo: "TES-TRIB-001",
    tipo: "tese",
    titulo: "Exclusão do ICMS da Base de Cálculo do PIS/COFINS",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "mandado_seguranca"],
    materias: ["tributario"],
    palavrasChave: ["ICMS", "PIS/COFINS", "base de cálculo", "Tema 69", "STF"],
    gatilhos: [
      { id: "GAT-TRIB-001", tipo: "palavra_chave", valor: "ICMS", peso: 5 },
      { id: "GAT-TRIB-002", tipo: "palavra_chave", valor: "PIS/COFINS", peso: 5 },
    ],
    teseBase: "O ICMS não compõe a base de cálculo do PIS e da COFINS, por não configurar receita ou faturamento da empresa, nos termos do Tema 69 do STF — RE 574.706.",
    fundamentoSintetico: "RE 574.706/STF — Tema 69: ICMS fora da base do PIS/COFINS.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-trib-002-v1",
    codigo: "TES-TRIB-002",
    tipo: "tese",
    titulo: "Compensação de Indébito Tributário",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "mandado_seguranca"],
    materias: ["tributario"],
    palavrasChave: ["compensação", "indébito tributário", "restituição", "SEFAZ", "Receita Federal"],
    gatilhos: [
      { id: "GAT-TRIB-003", tipo: "palavra_chave", valor: "indébito", peso: 5 },
      { id: "GAT-TRIB-004", tipo: "estrategia", valor: "compensação", peso: 4 },
    ],
    teseBase: "O contribuinte que recolheu tributo a maior ou indevidamente tem direito à restituição ou à compensação com tributos vincendos, mediante habilitação perante a autoridade administrativa ou via mandado de segurança.",
    fundamentoSintetico: "Art. 165 e 170 do CTN c/c art. 74 da Lei 9.430/96.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-trib-003-v1",
    codigo: "TES-TRIB-003",
    tipo: "tese",
    titulo: "Suspensão da Exigibilidade do Crédito Tributário",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["mandado_seguranca", "peticao_inicial", "tutela_urgencia"],
    materias: ["tributario"],
    palavrasChave: ["suspensão", "exigibilidade", "liminar", "depósito integral", "recurso administrativo"],
    gatilhos: [
      { id: "GAT-TRIB-005", tipo: "palavra_chave", valor: "suspensão", peso: 5 },
      { id: "GAT-TRIB-006", tipo: "estrategia", valor: "exigibilidade", peso: 4 },
    ],
    teseBase: "A suspensão da exigibilidade do crédito tributário, obtida por liminar em mandado de segurança ou por depósito integral, impede a constituição de penhora, inscrição em dívida ativa e certidão negativa de débitos.",
    fundamentoSintetico: "Art. 151 do CTN — Causas de suspensão da exigibilidade do crédito tributário.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Empresarial ---
  {
    id: "tese-emp-001-v1",
    codigo: "TES-EMP-001",
    tipo: "tese",
    titulo: "Dissolução Parcial por Quebra de Affectio Societatis",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["empresarial"],
    palavrasChave: ["affectio societatis", "dissolução parcial", "exclusão de sócio", "saída voluntária"],
    gatilhos: [
      { id: "GAT-EMP-001", tipo: "palavra_chave", valor: "affectio societatis", peso: 5 },
      { id: "GAT-EMP-002", tipo: "estrategia", valor: "dissolução", peso: 4 },
    ],
    teseBase: "A quebra irreversível da affectio societatis autoriza a dissolução parcial da sociedade, com apuração de haveres do sócio retirante ou excluído, sem necessidade de liquidação total, preservando-se a empresa em funcionamento.",
    fundamentoSintetico: "Arts. 1.029 e 1.085 do CC c/c Súmula 638/STJ.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-emp-002-v1",
    codigo: "TES-EMP-002",
    tipo: "tese",
    titulo: "Apuração de Haveres com Critério de Valor Justo (Balanço de Determinação)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "manifestacao"],
    materias: ["empresarial"],
    palavrasChave: ["apuração de haveres", "balanço de determinação", "valor justo", "fundo de comércio"],
    gatilhos: [
      { id: "GAT-EMP-003", tipo: "palavra_chave", valor: "apuração de haveres", peso: 5 },
      { id: "GAT-EMP-004", tipo: "estrategia", valor: "balanço", peso: 3 },
    ],
    teseBase: "A apuração dos haveres do sócio retirante deve refletir o real valor econômico da sociedade, incluindo ativos intangíveis, fundo de comércio e perspectivas de rentabilidade, mediante balanço de determinação realizado por perito.",
    fundamentoSintetico: "Art. 1.031 do CC c/c entendimento do STJ sobre valorização integral dos haveres.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Ambiental ---
  {
    id: "tese-amb-001-v1",
    codigo: "TES-AMB-001",
    tipo: "tese",
    titulo: "Responsabilidade Objetiva por Dano Ambiental",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["ambiental"],
    palavrasChave: ["responsabilidade objetiva", "dano ambiental", "reparação integral", "poluidor-pagador"],
    gatilhos: [
      { id: "GAT-AMB-001", tipo: "palavra_chave", valor: "dano ambiental", peso: 5 },
      { id: "GAT-AMB-002", tipo: "estrategia", valor: "responsabilidade objetiva", peso: 4 },
    ],
    teseBase: "A responsabilidade por dano ambiental é objetiva (independe de culpa), solidária entre causadores e imprescritível quanto à reparação do dano ao meio ambiente, admitindo-se cumulação de reparação in natura e compensação pecuniária.",
    fundamentoSintetico: "Art. 14, §1º da Lei 6.938/81 c/c Súmula 623/STJ.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-amb-002-v1",
    codigo: "TES-AMB-002",
    tipo: "tese",
    titulo: "Princípio da Precaução e Inversão do Ônus Ambiental",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "tutela_urgencia", "mandado_seguranca"],
    materias: ["ambiental"],
    palavrasChave: ["precaução", "inversão do ônus", "risco ambiental", "licenciamento"],
    gatilhos: [
      { id: "GAT-AMB-003", tipo: "palavra_chave", valor: "precaução", peso: 5 },
      { id: "GAT-AMB-004", tipo: "estrategia", valor: "risco ambiental", peso: 4 },
    ],
    teseBase: "Em matéria ambiental, aplica-se o princípio da precaução, com inversão do ônus probatório ao potencial poluidor quando há risco de dano grave ou irreversível, cabendo a este demonstrar a segurança da atividade.",
    fundamentoSintetico: "Art. 225 da CF/88 c/c art. 14 da Lei 6.938/81 — Princípio da precaução.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Cível adicional ---
  {
    id: "tese-civ-003-v1",
    codigo: "TES-CIV-003",
    tipo: "tese",
    titulo: "Dano Moral por Abalo de Crédito sem Causa Legítima",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["civel", "consumidor", "bancario"],
    palavrasChave: ["dano moral", "abalo de crédito", "negativação", "inscrição indevida"],
    gatilhos: [
      { id: "GAT-CIV-008", tipo: "palavra_chave", valor: "abalo de crédito", peso: 5 },
      { id: "GAT-CIV-009", tipo: "estrategia", valor: "dano moral", peso: 4 },
    ],
    teseBase: "O abalo de crédito causado por ato ilícito do réu gera dano moral presumido (in re ipsa), dispensando prova concreta do prejuízo, com fixação equitativa da indenização pelo juiz.",
    fundamentoSintetico: "Arts. 186 e 927 do CC c/c Súmula 385 do STJ.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-civ-004-v1",
    codigo: "TES-CIV-004",
    tipo: "tese",
    titulo: "Responsabilidade Civil por Nexo de Causalidade Adequada",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "apelacao_civel"],
    materias: ["civel"],
    palavrasChave: ["nexo causal", "causalidade adequada", "responsabilidade civil", "dano"],
    gatilhos: [
      { id: "GAT-CIV-010", tipo: "ponto_controvertido", valor: "nexo causal", peso: 5 },
      { id: "GAT-CIV-011", tipo: "estrategia", valor: "causalidade", peso: 4 },
    ],
    teseBase: "A responsabilidade civil exige a prova do nexo de causalidade adequada entre a conduta ilícita do réu e o dano sofrido pelo autor, sendo imputáveis apenas os danos que a conduta era apta a produzir.",
    fundamentoSintetico: "Arts. 186 e 403 do CC — Teoria da causalidade adequada.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Criminal ---
  {
    id: "tese-crim-001-v1",
    codigo: "TES-CRIM-001",
    tipo: "tese",
    titulo: "Ilegalidade de Prisão Preventiva — Excesso de Prazo e Proporcionalidade",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["habeas_corpus", "peticao_inicial"],
    materias: ["criminal"],
    palavrasChave: ["habeas corpus", "prisão preventiva", "excesso de prazo", "proporcionalidade", "ilegalidade da prisão"],
    gatilhos: [
      { id: "GAT-CRIM-001", tipo: "palavra_chave", valor: "prisão preventiva", peso: 5 },
      { id: "GAT-CRIM-002", tipo: "estrategia", valor: "excesso de prazo", peso: 5 },
    ],
    teseBase: "A prisão preventiva é medida de exceção que exige fundamentação concreta e atual sobre os requisitos do art. 312 do CPP (garantia da ordem pública, conveniência da instrução ou aplicação da lei penal). O excesso de prazo sem julgamento ou a fundamentação genérica/padronizada violam os princípios da presunção de inocência e proporcionalidade, autorizando a concessão de habeas corpus.",
    fundamentoSintetico: "Arts. 312 e 315, CPP c/c art. 5.º, LVII e LXVIII, CF/88 — Proporcionalidade e fundamento concreto para prisão cautelar.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-crim-002-v1",
    codigo: "TES-CRIM-002",
    tipo: "tese",
    titulo: "Substituição de Pena Privativa por Restritiva de Direitos",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao"],
    materias: ["criminal"],
    palavrasChave: ["pena alternativa", "restritiva de direitos", "substituição de pena", "primariedade", "bons antecedentes"],
    gatilhos: [
      { id: "GAT-CRIM-003", tipo: "palavra_chave", valor: "pena alternativa", peso: 5 },
      { id: "GAT-CRIM-004", tipo: "estrategia", valor: "substituição de pena", peso: 5 },
    ],
    teseBase: "O réu primário, com bons antecedentes, condenado a pena não superior a 4 anos (ou qualquer pena se crime culposo), que não usou violência ou grave ameaça, tem direito à substituição da pena privativa de liberdade por restritivas de direitos, desde que a medida seja suficiente para reprovação e prevenção do crime (art. 44, CP).",
    fundamentoSintetico: "Art. 44 e incisos do Código Penal — Substituição de pena privativa de liberdade.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-crim-003-v1",
    codigo: "TES-CRIM-003",
    tipo: "tese",
    titulo: "Desclassificação por Ausência de Elemento Subjetivo do Tipo",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["contestacao", "apelacao_civel", "peticao_inicial"],
    materias: ["criminal"],
    palavrasChave: ["desclassificação", "dolo", "culpa", "elemento subjetivo", "tipicidade subjetiva"],
    gatilhos: [
      { id: "GAT-CRIM-005", tipo: "palavra_chave", valor: "desclassificação", peso: 5 },
      { id: "GAT-CRIM-006", tipo: "ponto_controvertido", valor: "dolo vs culpa", peso: 5 },
    ],
    teseBase: "A adequação típica exige a presença do elemento subjetivo (dolo ou culpa). Ausente o dolo específico exigido pelo tipo penal imputado, cabe desclassificação para crime culposo (quando previsto) ou absolvição por atipicidade. A prova do elemento subjetivo é ônus da acusação.",
    fundamentoSintetico: "Art. 18, CP — Tipicidade subjetiva; princípio da culpabilidade; art. 156, CPP — ônus probatório da acusação.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-crim-004-v1",
    codigo: "TES-CRIM-004",
    tipo: "tese",
    titulo: "Absolvição por Ausência de Prova Suficiente — In Dubio Pro Reo",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "apelacao_civel", "habeas_corpus"],
    materias: ["criminal"],
    palavrasChave: ["in dubio pro reo", "absolvição", "prova insuficiente", "presunção de inocência", "dúvida razoável"],
    gatilhos: [
      { id: "GAT-CRIM-007", tipo: "estrategia", valor: "in dubio pro reo", peso: 5 },
      { id: "GAT-CRIM-008", tipo: "palavra_chave", valor: "prova insuficiente", peso: 5 },
    ],
    teseBase: "Em face da insuficiência de provas para uma condenação segura, aplica-se o princípio constitucional da presunção de inocência e do in dubio pro reo: na dúvida sobre autoria ou materialidade, o réu deve ser absolvido. A mera probabilidade ou indícios não robustos não sustentam condenação criminal.",
    fundamentoSintetico: "Art. 5.º, LVII, CF/88 c/c art. 386, VII, CPP — In dubio pro reo e absolvição por insuficiência de provas.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // NOVAS TESES — AGRÁRIO E BANCÁRIO (enriquecimento especializado)
  // ──────────────────────────────────────────────────────────────────────────

  // --- Agrário: execução de títulos ---
  {
    id: "tese-agr-008-v1",
    codigo: "TES-AGR-008",
    tipo: "tese",
    titulo: "Prorrogação Automática do Crédito Rural — Obsta Mora (Tema 1099/STJ)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "excecao_pre_executividade", "contestacao"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["prorrogação automática", "crédito rural", "mora", "Tema 1099", "STJ"],
    gatilhos: [
      { id: "GAT-AGR-022", tipo: "palavra_chave", valor: "prorrogação automática", peso: 5 },
      { id: "GAT-AGR-023", tipo: "palavra_chave", valor: "Tema 1099", peso: 5 },
      { id: "GAT-AGR-024", tipo: "estrategia", valor: "mora", peso: 3 },
    ],
    teseBase: "Quando o crédito rural é objeto de prorrogação automática prevista em normativo do MCR/BACEN ou em lei específica, a mora não se configura enquanto não cumprido o procedimento legal de formalização da prorrogação. A cobrança de encargos moratórios antes desse momento é indevida.",
    fundamentoSintetico: "Tema 1099/STJ c/c Manual de Crédito Rural (MCR/BACEN) — prorrogação automática como condição de configuração da mora.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-009-v1",
    codigo: "TES-AGR-009",
    tipo: "tese",
    titulo: "Prorrogação Automática do Arrendamento Rural pelo Prazo Mínimo Legal",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["contestacao", "peticao_inicial"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["arrendamento rural", "prorrogação automática", "prazo mínimo", "Estatuto da Terra"],
    gatilhos: [
      { id: "GAT-AGR-025", tipo: "palavra_chave", valor: "arrendamento", peso: 4 },
      { id: "GAT-AGR-026", tipo: "estrategia", valor: "prorrogação", peso: 4 },
      { id: "GAT-AGR-027", tipo: "referencia_documental", valor: "Decreto 59.566", peso: 3 },
    ],
    teseBase: "O contrato de arrendamento rural prorroga-se automaticamente pelo mesmo prazo do contrato original ao término sem denúncia prévia válida. O prazo mínimo legal é de 3 anos para lavoura temporária e 5 anos para lavoura permanente, pecuária ou reflorestamento. Contratos com prazo inferior ao mínimo legal são nulos na cláusula restritiva, prevalecendo o prazo mínimo.",
    fundamentoSintetico: "Art. 95, II e III, Estatuto da Terra c/c arts. 21 e 22 do Decreto 59.566/1966.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-agr-010-v1",
    codigo: "TES-AGR-010",
    tipo: "tese",
    titulo: "Notificação de Retomada de Arrendamento — Prazo de 6 Meses e Forma",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["agrario_agronegocio"],
    palavrasChave: ["notificação extrajudicial", "retomada", "arrendamento", "6 meses", "Estatuto da Terra"],
    gatilhos: [
      { id: "GAT-AGR-028", tipo: "palavra_chave", valor: "notificação de retomada", peso: 5 },
      { id: "GAT-AGR-029", tipo: "referencia_documental", valor: "art. 95, XII", peso: 4 },
      { id: "GAT-AGR-030", tipo: "estrategia", valor: "retomada", peso: 3 },
    ],
    teseBase: "A retomada do imóvel rural arrendado exige notificação extrajudicial ao arrendatário com antecedência mínima de 6 meses do término do contrato. A notificação deve indicar expressamente o motivo da retomada (uso direto, transferência de domínio, etc.). Ausência ou vício na notificação impede o pedido de retomada e configura prorrogação automática.",
    fundamentoSintetico: "Art. 95, XII e XIII, Estatuto da Terra (Lei 4.504/1964).",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },

  // --- Bancário: sub-casos especializados ---
  {
    id: "tese-ban-002-v1",
    codigo: "TES-BAN-002",
    tipo: "tese",
    titulo: "CDC Aplicável às Instituições Financeiras (Súmula 297/STJ)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "embargos_execucao"],
    materias: ["bancario"],
    palavrasChave: ["CDC", "instituições financeiras", "Súmula 297", "relação de consumo", "consumidor"],
    gatilhos: [
      { id: "GAT-BAN-004", tipo: "palavra_chave", valor: "CDC", peso: 4 },
      { id: "GAT-BAN-005", tipo: "palavra_chave", valor: "Súmula 297", peso: 5 },
      { id: "GAT-BAN-006", tipo: "estrategia", valor: "relação de consumo", peso: 3 },
    ],
    teseBase: "O Código de Defesa do Consumidor aplica-se às instituições financeiras em todas as suas operações (Súmula 297/STJ). Isso implica inversão do ônus da prova, vedação de cláusulas abusivas e responsabilidade objetiva pelo fato do serviço. O banco deve demonstrar que as condições contratadas são equitativas e que não houve prática abusiva.",
    fundamentoSintetico: "Súmula 297/STJ c/c arts. 2º, 3º e 51 do CDC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-003-v1",
    codigo: "TES-BAN-003",
    tipo: "tese",
    titulo: "Anatocismo — Capitalização de Juros Não Expressamente Pactuada",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "embargos_execucao", "contestacao"],
    materias: ["bancario"],
    palavrasChave: ["anatocismo", "capitalização de juros", "juros sobre juros", "pactuação expressa"],
    gatilhos: [
      { id: "GAT-BAN-007", tipo: "palavra_chave", valor: "anatocismo", peso: 5 },
      { id: "GAT-BAN-008", tipo: "palavra_chave", valor: "capitalização", peso: 4 },
      { id: "GAT-BAN-009", tipo: "ponto_controvertido", valor: "juros sobre juros", peso: 4 },
    ],
    teseBase: "A capitalização de juros em período inferior a um ano somente é admitida quando expressamente pactuada no contrato (Súmula 596/STJ). Na ausência de cláusula expressa, prevalece a vedação do art. 591 do CC. A revisão da planilha de evolução do débito pode revelar anatocismo velado por taxa diária equivalente à taxa mensal contratada.",
    fundamentoSintetico: "Art. 591 do CC c/c Súmula 596/STJ e MP 1.963-17/2000.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-004-v1",
    codigo: "TES-BAN-004",
    tipo: "tese",
    titulo: "Seguro Embutido Não Autorizado — Venda Casada Ilegal",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "embargos_execucao"],
    materias: ["bancario"],
    palavrasChave: ["seguro embutido", "venda casada", "prestamista", "Súmula 530", "prática abusiva"],
    gatilhos: [
      { id: "GAT-BAN-010", tipo: "palavra_chave", valor: "seguro embutido", peso: 5 },
      { id: "GAT-BAN-011", tipo: "palavra_chave", valor: "venda casada", peso: 5 },
      { id: "GAT-BAN-012", tipo: "referencia_documental", valor: "Súmula 530", peso: 4 },
    ],
    teseBase: "A cobrança de seguro prestamista, seguro de vida ou DFI embutido em contrato bancário sem que o devedor tenha contratado expressamente e voluntariamente configura venda casada vedada pelo CDC. Incumbe ao banco provar que o seguro foi contratado livremente (Súmula 530/STJ). O valor pago deve ser restituído ou abatido do saldo devedor.",
    fundamentoSintetico: "Súmula 530/STJ c/c art. 39, I, do CDC — Vedação de venda casada.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-005-v1",
    codigo: "TES-BAN-005",
    tipo: "tese",
    titulo: "Exceção de Pré-Executividade — Nulidade ou Prescrição do Título Bancário",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["excecao_pre_executividade", "embargos_execucao"],
    materias: ["bancario", "civel"],
    palavrasChave: ["exceção de pré-executividade", "prescrição", "nulidade do título", "CCB", "sem dilação probatória"],
    gatilhos: [
      { id: "GAT-BAN-013", tipo: "palavra_chave", valor: "pré-executividade", peso: 5 },
      { id: "GAT-BAN-014", tipo: "estrategia", valor: "nulidade do título", peso: 5 },
      { id: "GAT-BAN-015", tipo: "ponto_controvertido", valor: "prescrição", peso: 4 },
    ],
    teseBase: "A exceção de pré-executividade é cabível para arguir matérias de ordem pública cognoscíveis sem dilação probatória: prescrição da pretensão executória (5 anos — art. 206, §5º, I, CC), nulidade formal do título (CCB sem planilha de evolução do débito — art. 28, Lei 10.931/04), ilegitimidade passiva e excesso de execução aferível pelos próprios autos.",
    fundamentoSintetico: "Art. 206, §5º, I, CC c/c art. 28 da Lei 10.931/04 — Exceção de pré-executividade em execuções bancárias.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-006-v1",
    codigo: "TES-BAN-006",
    tipo: "tese",
    titulo: "Dano Moral por Negativação Indevida — In Re Ipsa",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["bancario", "consumidor"],
    palavrasChave: ["negativação indevida", "dano moral", "in re ipsa", "SERASA", "SPC", "Súmula 385"],
    gatilhos: [
      { id: "GAT-BAN-016", tipo: "palavra_chave", valor: "negativação indevida", peso: 5 },
      { id: "GAT-BAN-017", tipo: "estrategia", valor: "dano moral", peso: 4 },
      { id: "GAT-BAN-018", tipo: "referencia_documental", valor: "Súmula 385", peso: 4 },
    ],
    teseBase: "A inscrição indevida em cadastro de inadimplentes (SERASA, SPC, BACEN/SCR) configura dano moral in re ipsa quando o devedor não possuía outras inscrições legítimas anteriores. Dispensada a prova do efetivo prejuízo. Havendo anotações preexistentes e legítimas, aplica-se a Súmula 385/STJ, afastando o dano presumido — mas não o dano concreto, se provado.",
    fundamentoSintetico: "Arts. 5º, X, CF/88 c/c arts. 6º, VI e 43 do CDC c/c Súmula 385/STJ.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-ban-007-v1",
    codigo: "TES-BAN-007",
    tipo: "tese",
    titulo: "Revisão Contratual por Onerosidade Excessiva (Teoria da Imprevisão)",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["bancario", "civel"],
    palavrasChave: ["onerosidade excessiva", "teoria da imprevisão", "revisão contratual", "desequilíbrio", "pandemia", "câmbio"],
    gatilhos: [
      { id: "GAT-BAN-019", tipo: "palavra_chave", valor: "onerosidade excessiva", peso: 5 },
      { id: "GAT-BAN-020", tipo: "estrategia", valor: "revisão contratual", peso: 4 },
      { id: "GAT-BAN-021", tipo: "ponto_controvertido", valor: "desequilíbrio contratual", peso: 4 },
    ],
    teseBase: "Eventos supervenientes extraordinários e imprevisíveis que tornem a prestação excessivamente onerosa para uma das partes autorizam a revisão judicial do contrato, para reequilíbrio das obrigações. Exige-se: (i) contrato de execução diferida ou continuada; (ii) evento imprevisível posterior à celebração; (iii) onerosidade excessiva não decorrente do próprio risco contratual.",
    fundamentoSintetico: "Arts. 317, 478 e 480 do CC — Teoria da Imprevisão e revisão contratual por onerosidade excessiva.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },

  // ─── OPERAÇÃO MATA-MATA — Teses especializadas (TES-MM-001 a TES-MM-007) ───

  {
    id: "tese-mm-001-v1",
    codigo: "TES-MM-001",
    tipo: "tese",
    titulo: "Nulidade da Operação Mata-Mata — Simulação e Desvio de Finalidade do Crédito Rural",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "excecao_pre_executividade", "contestacao"],
    materias: ["bancario", "agrario_agronegocio"],
    palavrasChave: [
      "operação mata-mata", "rolagem de crédito", "simulação", "desvio de finalidade",
      "crédito rural", "CCB", "liquidação de débito pretérito", "nulidade",
    ],
    gatilhos: [
      { id: "GAT-MM-001", tipo: "palavra_chave", valor: "operação mata-mata", peso: 5 },
      { id: "GAT-MM-002", tipo: "palavra_chave", valor: "rolagem de crédito", peso: 5 },
      { id: "GAT-MM-003", tipo: "padrao_textual", valor: "novo contrato para pagar dívida anterior", peso: 5 },
      { id: "GAT-MM-004", tipo: "ponto_controvertido", valor: "disponibilidade real dos recursos", peso: 4 },
      { id: "GAT-MM-005", tipo: "estrategia", valor: "simulação de crédito produtivo", peso: 4 },
      { id: "GAT-MM-006", tipo: "referencia_documental", valor: "extrato de liquidação simultânea", peso: 5 },
    ],
    teseBase: "A concessão de novo crédito rural (CCB ou CCR) para liquidar débito pretérito do mesmo produtor, sem disponibilização real dos recursos para fomento de atividade produtiva, configura negócio jurídico simulado (art. 167 do CC) com desvio de finalidade do crédito rural regulado (art. 49 do DL 167/67). O título executivo oriundo dessa operação é nulo de pleno direito, pois mascara mera rolagem de dívida como se fosse crédito novo destinado à produção.",
    fundamentoSintetico: "Arts. 166, VI, e 167 do CC (simulação); art. 49 do DL 167/67 (finalidade do crédito rural); REsp 1.061.530/RS.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-002-v1",
    codigo: "TES-MM-002",
    tipo: "tese",
    titulo: "Revisão da Cadeia de Crédito Rural — Súmula 286/STJ",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "peticao_inicial", "contestacao", "apelacao_civel"],
    materias: ["bancario", "agrario_agronegocio"],
    palavrasChave: [
      "cadeia de crédito", "renegociação", "novação", "Súmula 286/STJ",
      "encargos anteriores", "repactuação", "revisão contratual",
    ],
    gatilhos: [
      { id: "GAT-MM-007", tipo: "referencia_documental", valor: "contrato anterior liquidado", peso: 5 },
      { id: "GAT-MM-008", tipo: "palavra_chave", valor: "renegociação", peso: 4 },
      { id: "GAT-MM-009", tipo: "padrao_textual", valor: "encargos da operação original", peso: 4 },
      { id: "GAT-MM-010", tipo: "estrategia", valor: "revisão da cadeia de crédito", peso: 5 },
      { id: "GAT-MM-011", tipo: "ponto_controvertido", valor: "novação com encargos ilegais", peso: 4 },
    ],
    teseBase: "Pela Súmula 286/STJ, 'a renegociação de contrato bancário ou a confissão de dívida não impede a possibilidade de discussão sobre eventuais ilegalidades dos contratos anteriores'. A cadeia de operações que culmina na Operação Mata-Mata pode — e deve — ser integralmente revisada. A novação formal não apaga encargos ilegais incorporados nas renegociações anteriores, especialmente juros acima dos limites do crédito rural.",
    fundamentoSintetico: "Súmula 286/STJ; arts. 360 a 367 do CC (novação); art. 49 do DL 167/67.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-003-v1",
    codigo: "TES-MM-003",
    tipo: "tese",
    titulo: "Direito ao Alongamento/Securitização — Súmula 298/STJ e MCR",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "mandado_seguranca", "peticao_inicial", "tutela_urgencia"],
    materias: ["agrario_agronegocio", "bancario"],
    palavrasChave: [
      "alongamento", "securitização", "Súmula 298/STJ", "MCR", "crédito rural controlado",
      "prorrogação", "recursos obrigatórios", "mandado de segurança",
    ],
    gatilhos: [
      { id: "GAT-MM-012", tipo: "palavra_chave", valor: "alongamento", peso: 5 },
      { id: "GAT-MM-013", tipo: "palavra_chave", valor: "securitização", peso: 5 },
      { id: "GAT-MM-014", tipo: "estrategia", valor: "prorrogação de crédito rural controlado", peso: 5 },
      { id: "GAT-MM-015", tipo: "referencia_documental", valor: "Manual de Crédito Rural MCR", peso: 4 },
      { id: "GAT-MM-016", tipo: "ponto_controvertido", valor: "recusa de alongamento pelo banco", peso: 5 },
    ],
    teseBase: "A Súmula 298/STJ estabelece que 'o alongamento de dívida rural é viável mesmo sem a concordância do credor originário', quando preenchidos os requisitos do Manual de Crédito Rural (MCR/BACEN) e da legislação de securitização (Lei 9.138/95). O banco que concede crédito com recursos controlados do MCR está vinculado às regras de prorrogação obrigatória. A recusa ilegal ao alongamento justifica Mandado de Segurança no prazo decadencial de 120 dias do ato coator.",
    fundamentoSintetico: "Súmula 298/STJ; Lei 9.138/95 (securitização rural); MCR/BACEN; Decreto-Lei 167/67.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-004-v1",
    codigo: "TES-MM-004",
    tipo: "tese",
    titulo: "Limitação de Juros em Crédito Rural — DL 167/67 e Decreto 22.626/33",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "peticao_inicial", "excecao_pre_executividade", "contestacao"],
    materias: ["bancario", "agrario_agronegocio"],
    palavrasChave: [
      "juros crédito rural", "limite de juros", "DL 167/67", "taxa referencial",
      "encargos abusivos", "Decreto 22.626/33", "usura",
    ],
    gatilhos: [
      { id: "GAT-MM-017", tipo: "palavra_chave", valor: "juros crédito rural", peso: 5 },
      { id: "GAT-MM-018", tipo: "padrao_textual", valor: "taxa acima do limite legal do crédito rural", peso: 5 },
      { id: "GAT-MM-019", tipo: "referencia_documental", valor: "planilha de cálculo de encargos", peso: 4 },
      { id: "GAT-MM-020", tipo: "estrategia", valor: "limitação de juros pela legislação especial", peso: 4 },
      { id: "GAT-MM-021", tipo: "ponto_controvertido", valor: "capitalização mensal em crédito rural", peso: 4 },
    ],
    teseBase: "As operações de crédito rural reguladas pelo DL 167/67 estão sujeitas a limitação de encargos fixada pelo Conselho Monetário Nacional (CMN), não se aplicando, nesse caso, a liberação geral de juros bancários. A cobrança de taxas acima do limite do MCR ou a capitalização não expressamente autorizada para crédito rural configura encargo abusivo, sujeito a revisão e expurgo. O Decreto 22.626/33 (Lei de Usura) continua a reger operações rurais com recursos controlados.",
    fundamentoSintetico: "Art. 5º e art. 49 do DL 167/67; Decreto 22.626/33; Resoluções CMN sobre taxas de crédito rural.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-005-v1",
    codigo: "TES-MM-005",
    tipo: "tese",
    titulo: "Nulidade de Indexação por CDI em Crédito Rural — Súmula 176/STJ",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "peticao_inicial", "excecao_pre_executividade", "contestacao"],
    materias: ["bancario", "agrario_agronegocio"],
    palavrasChave: [
      "CDI", "indexação", "Súmula 176/STJ", "nulidade", "taxa referencial",
      "correção monetária", "encargo ilegal",
    ],
    gatilhos: [
      { id: "GAT-MM-022", tipo: "palavra_chave", valor: "CDI", peso: 5 },
      { id: "GAT-MM-023", tipo: "padrao_textual", valor: "correção pelo CDI", peso: 5 },
      { id: "GAT-MM-024", tipo: "referencia_documental", valor: "cláusula de indexação contratual", peso: 4 },
      { id: "GAT-MM-025", tipo: "estrategia", valor: "substituição de CDI por índice oficial", peso: 4 },
      { id: "GAT-MM-026", tipo: "ponto_controvertido", valor: "legalidade do CDI como indexador", peso: 4 },
    ],
    teseBase: "A Súmula 176/STJ declara ser 'nula a cláusula contratual que sujeita o devedor à taxa de juros divulgada pela ANBID/CETIP'. Em crédito rural, a cláusula de indexação ao CDI é duplamente nula: (i) pela Súmula 176/STJ, por não se tratar de índice oficial; (ii) pelo DL 167/67, que vincula os encargos rurais às resoluções do CMN. A nulidade impõe substituição pelo índice oficial de correção monetária aplicável.",
    fundamentoSintetico: "Súmula 176/STJ; art. 5º do DL 167/67; arts. 406 e 591 do CC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-006-v1",
    codigo: "TES-MM-006",
    tipo: "tese",
    titulo: "Mora Limitada a 1% a.a. em Crédito Rural — Art. 5º do DL 167/67",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "excecao_pre_executividade", "contestacao", "peticao_inicial"],
    materias: ["bancario", "agrario_agronegocio"],
    palavrasChave: [
      "mora", "juros moratórios", "1% ao ano", "DL 167/67", "crédito rural",
      "multa moratória", "comissão de permanência",
    ],
    gatilhos: [
      { id: "GAT-MM-027", tipo: "palavra_chave", valor: "mora crédito rural", peso: 5 },
      { id: "GAT-MM-028", tipo: "padrao_textual", valor: "juros de mora acima de 1%", peso: 5 },
      { id: "GAT-MM-029", tipo: "referencia_documental", valor: "planilha de mora e encargos", peso: 4 },
      { id: "GAT-MM-030", tipo: "estrategia", valor: "limitação legal da mora rural", peso: 4 },
      { id: "GAT-MM-031", tipo: "ponto_controvertido", valor: "comissão de permanência ilegal", peso: 4 },
    ],
    teseBase: "O art. 5º do Decreto-Lei 167/67 limita os juros de mora em operações de crédito rural a 1% ao ano. Qualquer encargo moratório superior a esse teto — incluindo comissão de permanência, multa contratual cumulada com juros moratórios ou capitalização de mora — é nulo de pleno direito. Na Operação Mata-Mata, esse vício costuma se acumular ao longo de toda a cadeia de renegociações, tornando o saldo devedor final significativamente superior ao exigível.",
    fundamentoSintetico: "Art. 5º do DL 167/67; Súmula 294/STJ (comissão de permanência); Súmula 296/STJ (cumulação proibida).",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "tese-mm-007-v1",
    codigo: "TES-MM-007",
    tipo: "tese",
    titulo: "Impenhorabilidade do Produto Rural Vinculado a CPR/CCR",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["embargos_execucao", "agravo_instrumento", "excecao_pre_executividade", "impugnacao"],
    materias: ["agrario_agronegocio", "bancario"],
    palavrasChave: [
      "impenhorabilidade", "CPR", "CCR", "produto rural vinculado", "penhor rural",
      "bem essencial", "atividade produtiva",
    ],
    gatilhos: [
      { id: "GAT-MM-032", tipo: "palavra_chave", valor: "impenhorabilidade produto rural", peso: 5 },
      { id: "GAT-MM-033", tipo: "padrao_textual", valor: "penhora sobre colheita vinculada a CPR", peso: 5 },
      { id: "GAT-MM-034", tipo: "referencia_documental", valor: "CPR ou CCR com penhor constituído", peso: 4 },
      { id: "GAT-MM-035", tipo: "estrategia", valor: "proteção do bem essencial à atividade agrícola", peso: 4 },
      { id: "GAT-MM-036", tipo: "ponto_controvertido", valor: "dupla vinculação do produto rural", peso: 5 },
    ],
    teseBase: "O produto rural objeto de Cédula de Produto Rural (CPR) ou dado em penhor em Cédula de Crédito Rural (CCR) é impenhorável por credor sem preferência sobre aquele bem específico. A execução por banco diverso ou por dívida não vinculada àquele contrato não pode recair sobre colheita ou produto já onerado. A penhorabilidade encontra limite no art. 17 do DL 167/67 (penhor rural cedularizado) e na Lei 8.929/94 (CPR). Em casos de Operação Mata-Mata, o produto que seria destinado ao pagamento do crédito legítimo não pode ser penhorado pelo crédito simulado.",
    fundamentoSintetico: "Art. 17 do DL 167/67; arts. 1 e 16 da Lei 8.929/94 (CPR); art. 833, IV e V, do CPC.",
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
];

const CHECKLISTS_PADRAO: ChecklistJuridicoAtivoVersionado[] = [
  {
    id: "checklist-obr-001-v1",
    codigo: "CHK-OBR-001",
    tipo: "checklist",
    descricao: "Qualificação das partes está explícita.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "obrigatorio",
    blocoEsperado: "qualificacao_identificacao",
    tokensEsperados: ["partes", "cliente", "caso"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-obr-002-v1",
    codigo: "CHK-OBR-002",
    tipo: "checklist",
    descricao: "Síntese fática contém narrativa objetiva.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "obrigatorio",
    blocoEsperado: "sintese_fatica",
    tokensEsperados: ["fatos", "cronologia", "evento"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-obr-003-v1",
    codigo: "CHK-OBR-003",
    tipo: "checklist",
    descricao: "Fundamentos jurídicos foram estruturados.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["fundamento", "estratégia", "juríd"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-obr-004-v1",
    codigo: "CHK-OBR-004",
    tipo: "checklist",
    descricao: "Pedidos estão claros e determinados.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "obrigatorio",
    blocoEsperado: "pedidos",
    tokensEsperados: ["pedido", "requer", "procedência", "improcedência"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-rec-001-v1",
    codigo: "CHK-REC-001",
    tipo: "checklist",
    descricao: "Referências documentais aparecem nos fundamentos ou pedidos.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "recomendavel",
    blocoEsperado: "geral",
    tokensEsperados: ["DOC-", "documento", "referência"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-rec-002-v1",
    codigo: "CHK-REC-002",
    tipo: "checklist",
    descricao: "Fechamento processual com fórmula final adequada.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "manifestacao", "embargos_execucao", "apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "recomendavel",
    blocoEsperado: "fechamento",
    tokensEsperados: ["pede deferimento", "termos em que"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-rec-003-v1",
    codigo: "CHK-REC-003",
    tipo: "checklist",
    descricao: "Peça recursal explicita pedido de reforma/admissibilidade.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["apelacao_civel", "recurso_especial_civel"],
    materias: ["civel", "agrario_agronegocio", "bancario"],
    categoria: "recomendavel",
    blocoEsperado: "pedidos",
    tokensEsperados: ["reforma", "admissão", "provimento"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-agr-001-v1",
    codigo: "CHK-AGR-001",
    tipo: "checklist",
    descricao: "Juntada de documentação fundiária essencial (Matrícula, CAR, CCIR).",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["agrario_agronegocio"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["matrícula", "CAR", "Cadastro Ambiental Rural", "CCIR"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-agr-002-v1",
    codigo: "CHK-AGR-002",
    tipo: "checklist",
    descricao: "Citação explícita aos laudos atestando exploração da área (fotos, relatórios técnicos, laudos pluviométricos).",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "embargos_execucao", "reconvencao", "manifestacao"],
    materias: ["agrario_agronegocio"],
    categoria: "recomendavel",
    blocoEsperado: "sintese_fatica",
    tokensEsperados: ["laudo", "vistoria", "fotografia", "safra", "clima", "chuvas"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-agr-003-v1",
    codigo: "CHK-AGR-003",
    tipo: "checklist",
    descricao: "Verificação do prazo semestral para notificação premonitória (Estatuto da Terra).",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["agrario_agronegocio"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["notificação", "prazo de seis meses", "semestre", "retomada", "art. 95"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Trabalhista ---
  {
    id: "checklist-trab-001-v1",
    codigo: "CHK-TRAB-001",
    tipo: "checklist",
    descricao: "CTPS ou prova documental do vínculo empregatício está referenciada.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["trabalhista"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["CTPS", "contrato de trabalho", "vínculo", "admissão"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-trab-002-v1",
    codigo: "CHK-TRAB-002",
    tipo: "checklist",
    descricao: "Cálculo de verbas trabalhistas e reflexos está especificado nos pedidos.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["trabalhista"],
    categoria: "obrigatorio",
    blocoEsperado: "pedidos",
    tokensEsperados: ["FGTS", "verbas rescisórias", "horas extras", "DSR", "13º"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Consumidor ---
  {
    id: "checklist-cons-001-v1",
    codigo: "CHK-CONS-001",
    tipo: "checklist",
    descricao: "Relação de consumo identificada com qualificação do fornecedor.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["consumidor"],
    categoria: "obrigatorio",
    blocoEsperado: "qualificacao_identificacao",
    tokensEsperados: ["fornecedor", "consumidor", "CDC", "produto", "serviço"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-cons-002-v1",
    codigo: "CHK-CONS-002",
    tipo: "checklist",
    descricao: "Comprovante do dano sofrido (nota fiscal, contrato, print, boletim) referenciado.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["consumidor"],
    categoria: "recomendavel",
    blocoEsperado: "sintese_fatica",
    tokensEsperados: ["nota fiscal", "recibo", "comprovante", "print", "boleto"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Família ---
  {
    id: "checklist-fam-001-v1",
    codigo: "CHK-FAM-001",
    tipo: "checklist",
    descricao: "Certidão de nascimento dos alimentandos juntada ou referenciada.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["familia"],
    categoria: "obrigatorio",
    blocoEsperado: "qualificacao_identificacao",
    tokensEsperados: ["certidão", "nascimento", "filhos", "menor"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  {
    id: "checklist-fam-002-v1",
    codigo: "CHK-FAM-002",
    tipo: "checklist",
    descricao: "Documentação de renda do alimentante (holerite, IRPF, extratos) mencionada.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao"],
    materias: ["familia"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["renda", "salário", "holerite", "IRPF", "rendimentos"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Tributário ---
  {
    id: "checklist-trib-001-v1",
    codigo: "CHK-TRIB-001",
    tipo: "checklist",
    descricao: "Comprovante de recolhimento do tributo ou auto de infração referenciado.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "mandado_seguranca"],
    materias: ["tributario"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["DARF", "guia", "auto de infração", "notificação fiscal", "SPED"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Ambiental ---
  {
    id: "checklist-amb-001-v1",
    codigo: "CHK-AMB-001",
    tipo: "checklist",
    descricao: "Auto de infração ambiental ou laudo técnico de dano referenciado.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial"],
    materias: ["ambiental"],
    categoria: "obrigatorio",
    blocoEsperado: "fundamentos",
    tokensEsperados: ["auto de infração", "laudo ambiental", "IBAMA", "SEMA", "licenciamento"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
  // --- Criminal ---
  {
    id: "checklist-crim-001-v1",
    codigo: "CHK-CRIM-001",
    tipo: "checklist",
    descricao: "Certidão de antecedentes criminais e eventual inquérito ou denúncia referenciados.",
    versao: 1,
    status: "ativo",
    tiposPecaCanonica: ["peticao_inicial", "contestacao", "habeas_corpus"],
    materias: ["criminal"],
    categoria: "obrigatorio",
    blocoEsperado: "qualificacao_identificacao",
    tokensEsperados: ["antecedentes", "inquérito", "denúncia", "boletim de ocorrência"],
    criadoEm: DATA_BASE_PADRAO,
    atualizadoEm: DATA_BASE_PADRAO,
  },
];

export function criarTemplatesJuridicosPadrao(): TemplateJuridicoAtivoVersionado[] {
  return structuredClone(TEMPLATES_PADRAO);
}

export function criarTesesJuridicasPadrao(): TeseJuridicaAtivaVersionada[] {
  return structuredClone(TESES_PADRAO);
}

export function criarChecklistsJuridicosPadrao(): ChecklistJuridicoAtivoVersionado[] {
  return structuredClone(CHECKLISTS_PADRAO);
}
